server:
  port: 8085

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'

eureka:
  instance:
    appname: ShrekTurbine
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: ShrekTurbine
  boot:
    admin:
      client:
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题
        url: http://localhost:8082/ # 向服务端注册的地址

turbine:
  app-config: ShrekConsumer,shrekApiGateway,shrekSupervisor#参数指定了需要收集监控信息的服务名
  cluster-name-expression:  default #参数指定了集群名称为default，当服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群
  combine-host-port:  true  #参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务