server:
  port: 8093

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://127.0.0.1:9411
  boot:
    admin:
      client:
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题
        url: http://localhost:8082/ # 向服务端注册的地址
  security:
    user:
      name: shrek
      password: shrek
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      user-authorization-uri: http://127.0.0.1:8088/oauth/authorize
      access-token-uri: http://127.0.0.1:8088/oauth/token
    resource:
      user-info-uri: http://127.0.0.1:8088/supervisor//user #返回认证服务器检查
#        prefer-token-info: false
      token-info-uri: http://127.0.0.1:8088/oauth/check_token
      prefer-token-info: true


# 显示sql
logging:
  level:
    com:
      shrek:
        supervisor: debug

info:
  app:
      name: "@project.artifactId@"
      encoding: '@project.build.sourceEncoding@'
      java:
        source: '@java.version@'
        target: '@java.version@'
